### ISSUE TITLE
Open for contributions?

### ISSUE THREAD

**Issue by infra-monkey** [RomanButsiy/terraform-provider-freeipa-2#1]
Hello,

I stumbled upon this provider today.
I have tested it a bit and i loved it. I was considering starting one too because the ansible stuff is so slow and brings it's own set of problems.

I was wondering how far you want to take the feature set and if you are open for external contribution.
All the "user feature" like sudo rules, idviews, id override as well as the host stuff would fit nicely in a terraform provider.

**Comment by RomanButsiy** [comment]
@infra-monkey Hello, sorry for the late reply
Use this terraform provider https://github.com/rework-space-com/terraform-provider-freeipa (I see you already found it).
Yes, I am ready for contributions. Tonight, if I have power, and internet, I will review and add your merge request

**Comment by infra-monkey** [comment]
Hi @RomanButsiy 
Not a problem, I understand the situation is hard.
I've done also hosts/hostgroup/membership, if you want i can make a MR for this.
I plan next to work on sudo stuff and hbac, if you are interested in those. And later the idviews and overrides, but maybe better to consolidate first.
